"""baseline

Revision ID: 2435ee38b6cb
Revises: 
Create Date: 2026-08-10 10:35:31.119385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2435ee38b6cb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('medicine_id'), table_name='inventory')
    op.drop_table('inventory')
    op.drop_table('sales')
    op.drop_table('sale_items')
    op.create_index(op.f('ix_categories_category_id'), 'categories', ['category_id'], unique=False)
    op.create_unique_constraint(None, 'categories', ['category_name'])
    op.drop_column('categories', 'description')
    op.alter_column('users', 'first_name',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('users', 'last_name',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('users', 'email',
               existing_type=mysql.VARCHAR(length=150),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('users', 'role',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=True,
               existing_server_default=sa.text("'Staff'"))
    op.alter_column('users', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('users', 'role',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True,
               existing_server_default=sa.text("'Staff'"))
    op.alter_column('users', 'email',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=150),
               existing_nullable=False)
    op.alter_column('users', 'last_name',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=False)
    op.alter_column('users', 'first_name',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=False)
    op.add_column('categories', sa.Column('description', mysql.TEXT(), nullable=True))
    op.drop_constraint(None, 'categories', type_='unique')
    op.drop_index(op.f('ix_categories_category_id'), table_name='categories')
    op.create_table('sale_items',
    sa.Column('sale_item_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('sale_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('medicine_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('quantity', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('price', mysql.DECIMAL(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['medicine_id'], ['medicines.medicine_id'], name=op.f('sale_items_ibfk_2')),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.sale_id'], name=op.f('sale_items_ibfk_1')),
    sa.PrimaryKeyConstraint('sale_item_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('sales',
    sa.Column('sale_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('customer_name', mysql.VARCHAR(length=150), nullable=True),
    sa.Column('sale_date', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('total_amount', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('sales_ibfk_1')),
    sa.PrimaryKeyConstraint('sale_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('inventory',
    sa.Column('inventory_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('medicine_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('quantity_available', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('minimum_stock_level', mysql.INTEGER(), server_default=sa.text("'10'"), autoincrement=False, nullable=True),
    sa.Column('last_updated', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['medicine_id'], ['medicines.medicine_id'], name=op.f('inventory_ibfk_1')),
    sa.PrimaryKeyConstraint('inventory_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('medicine_id'), 'inventory', ['medicine_id'], unique=True)
    # ### end Alembic commands ###
