"""add sale voiding and user deactivation

Revision ID: 440e1333c245
Revises: 7bad13f621e6
Create Date: 2026-08-13 10:03:19.553713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '440e1333c245'
down_revision: Union[str, Sequence[str], None] = '7bad13f621e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales', sa.Column('is_voided', sa.Boolean(), nullable=False))
    op.add_column('sales', sa.Column('voided_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_active')
    op.drop_column('sales', 'voided_at')
    op.drop_column('sales', 'is_voided')
    # ### end Alembic commands ###
