"""add category description and align schema

Revision ID: 7bad13f621e6
Revises: 2435ee38b6cb
Create Date: 2026-08-13 00:02:59.484799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '7bad13f621e6'
down_revision: Union[str, Sequence[str], None] = '2435ee38b6cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_categories_category_id'), 'categories', ['category_id'], unique=False)
    op.create_unique_constraint(None, 'categories', ['category_name'])
    op.alter_column('inventory', 'last_updated',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.create_index(op.f('ix_inventory_inventory_id'), 'inventory', ['inventory_id'], unique=False)
    op.create_index(op.f('ix_sale_items_sale_item_id'), 'sale_items', ['sale_item_id'], unique=False)
    op.alter_column('sales', 'sale_date',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_index(op.f('ix_sales_sale_id'), 'sales', ['sale_id'], unique=False)
    op.alter_column('users', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('ix_sales_sale_id'), table_name='sales')
    op.alter_column('sales', 'sale_date',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('ix_sale_items_sale_item_id'), table_name='sale_items')
    op.drop_index(op.f('ix_inventory_inventory_id'), table_name='inventory')
    op.alter_column('inventory', 'last_updated',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.drop_constraint(None, 'categories', type_='unique')
    op.drop_index(op.f('ix_categories_category_id'), table_name='categories')
    # ### end Alembic commands ###
